apiVersion: v1
kind: Service
metadata:
  name: core-api-service
spec:
  selector:
    app: core-api
  ports:
  - protocol: TCP
    port: 80  # Adjust the port as needed
    targetPort: 8080  # Update with the port your core-api application listens on
  type: NodePort 

