apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
      - name: core-api
        image: core-api
