apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: customer-portal
  template:
    metadata:
      labels:
        app: customer-portal
    spec:
      containers:
      - name: customer-portal
        image: customer-portal
