apiVersion: v1
kind: Service
metadata:
  name: customer-portal-service
spec:
  selector:
    app: customer-portal
  ports:
  - protocol: TCP
    port: 80  # Adjust the port as needed
    targetPort: 3000  # Update with the port your customer-portal application listens on
  type: NodePort 
