apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
      - name: customer-api
        image: customer-api
