apiVersion: v1
kind: Service
metadata:
  name: customer-api-service
spec:
  selector:
    app: customer-api
  ports:
  - protocol: TCP
    port: 80  # Adjust the port as needed
    targetPort: 8080  # Update with the port your customer-api application listens on
  type: NodePort 
