apiVersion: v1
kind: Service
metadata:
  name: new-sip-admin-service
spec:
  selector:
    app: new-sip-admin
  ports:
  - protocol: TCP
    port: 80  # Adjust the port as needed
    targetPort: 3001  # Update with the port your customer-portal application listens on
  type: NodePort
