apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-sip-admin
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: new-sip-admin
  template:
    metadata:
      labels:
        app: new-sip-admin
    spec:
      containers:
      - name: new-sip-admin
        image: new-sip-admin
